---
- name: "Restart nkf-proxy service"
  systemd:
    name: "nkf-proxy.service"
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: "Restart matterbridge service"
  systemd:
    name: "matterbridge.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
