---
nkf_proxy_port: 6668
irc_server_host: "irc.ircnet.ne.jp"
irc_server_port: 6667

matterbridge_version: "v1.12.2"
matterbridge_filename: "matterbridge-linux-arm"
matterbridge_sha256: "e233527c9c7f0bd01488eebdad62b39ce35930fe4074fff7af52d9ce10214bf3"

matterbridge_nick: "matterbridge"
matterbridge_toml: |
  [general]
  RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

  [[gateway]]
  name="nadoka-gateway"
  enable=true
  [[gateway.inout]]
  account="irc.freenode"
  channel="#nadoka_jp"
  [[gateway.inout]]
  account="irc.ircnet"
  channel="#nadoka:*.jp"

  [[gateway]]
  name="ruby-ja-gateway"
  enable=true
  [[gateway.inout]]
  account="irc.freenode"
  channel="#ruby-ja"
  [[gateway.inout]]
  account="irc.ircnet"
  channel="#ruby-ja"
