---
nkf_proxy_port: 6668
irc_server_host: "irc.ircnet.ne.jp"
irc_server_port: 6667

matterbridge_version: "v1.12.3"
matterbridge_filename: "matterbridge-linux-arm"
matterbridge_sha256: "2ecbc0bf9e2fb7a393cba392f45f6d9f638747968b844b8edc0188388be86617"

matterbridge_nick: "matterbridge"
matterbridge_toml: |
  [general]
  RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

  [[gateway]]
  name="nadoka-gateway"
  enable=true
  [[gateway.inout]]
  account="irc.freenode"
  channel="#nadoka_jp"
  [[gateway.inout]]
  account="irc.ircnet"
  channel="#nadoka:*.jp"

  [[gateway]]
  name="ruby-ja-gateway"
  enable=true
  [[gateway.inout]]
  account="irc.freenode"
  channel="#ruby-ja"
  [[gateway.inout]]
  account="irc.ircnet"
  channel="#ruby-ja"
