---
nkf_proxy_port: 6668
irc_server_host: "irc.ircnet.ne.jp"
irc_server_port: 6667

matterbridge_version: "v1.9.0"
matterbridge_filename: "matterbridge-linux-arm"
matterbridge_sha256: "9a9f3fc77e50aebe4678e2cd35bc13798afc4867e8e2491444359ba20c94b1e8"

matterbridge_nick: "matterbridge"
matterbridge_toml: |
  [general]
  RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

  [[gateway]]
  name="nadoka-gateway"
  enable=true

  [[gateway.inout]]
  account="irc.freenode"
  channel="#nadoka_jp"

  [[gateway.inout]]
  account="irc.ircnet"
  channel="#nadoka:*.jp"
