---
nkf_proxy_port: 6668
irc_server_host: "irc.ircnet.ne.jp"
irc_server_port: 6667

matterbridge_version: "v1.11.3"
matterbridge_filename: "matterbridge-linux-arm"
matterbridge_sha256: "ab9e49269b0c51f3d0b6f2f1b895ff080f7af240c1559c09f3d50568c535269c"

matterbridge_nick: "matterbridge"
matterbridge_toml: |
  [general]
  RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

  [[gateway]]
  name="nadoka-gateway"
  enable=true
  [[gateway.inout]]
  account="irc.freenode"
  channel="#nadoka_jp"
  [[gateway.inout]]
  account="irc.ircnet"
  channel="#nadoka:*.jp"

  [[gateway]]
  name="ruby-ja-gateway"
  enable=true
  [[gateway.inout]]
  account="irc.freenode"
  channel="#ruby-ja"
  [[gateway.inout]]
  account="irc.ircnet"
  channel="#ruby-ja"
